### ISSUE TITLE
Help routines for initialising ssl sockets

### ISSUE THREAD

**Issue by mmzeeman** [zotonic/zotonic_ssl#3]
Over the various erlang releases there have been a lot of changes in the cipher_suites and the way you need to configure your ssl listen socket securely.

Having learned from the code we have in zotonic/mochiweb which collects all available safe suites from erlang and provide a sorted list of ciphers I would like to add this mechanism to zotonic_ssl.

I would like to be able to easily disable unsafe algorithms, protocol versions, and sort the suites bases on the rules defined by: 
https://english.ncsc.nl/publications/publications/2019/juni/01/it-security-guidelines-for-transport-layer-security-tls

Functionality needed, which works for OTP 18, 19, 20, 21, 22 and 23 are:

- [x] A function to return the safe tls protocol versions provided by the currently supported erlang release. 
- [x] A filter function which can be used to remove known unsafe cipher suites from a list.
- [x] A sort function which can be used to sort cipher suites from preferred to less preferred.
- [ ] A function which can be used to return a sorted list of safe cipher suites provided by the erlang system.

**Comment by mworrell** [comment]
I am not sure which OTP versions the external users of zotonic_ssl are using.

Zotonic (master) is currently at minimum of OTP 21.3

**Comment by mmzeeman** [comment]
Good one... the rebar.config now set to 18 as minimum version
